# Generated by Django 4.1.3 on 2022-11-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dbuser',
            field=models.CharField(default='user293', max_length=100),
            preserve_default=False,
        ),
    ]
