# Generated by Django 4.1.3 on 2022-11-27 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isprofile', '0002_employee_dbuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': (('can_see_db', 'Can see db settings'),)},
        ),
    ]
